In [1]:
import torch

In [2]:
def sigmodal_activation(x):
    return 1/(1 + torch.exp(-x))

When you want output of your NN a probability, sigmoidal activation function is what you need to use

In [3]:
torch.manual_seed(7)

In [4]:
features = torch.randn((1,5))

In [5]:
features

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])

In [6]:
weights = torch.randn_like(features)

In [7]:
weights

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [8]:
bias = torch.randn((1, 1))

In [9]:
bias

tensor([[0.3177]])

randn() is used for generating random normal variables i.e. random variables with normal distribution.

In [10]:
features.shape

torch.Size([1, 5])

In [11]:
weights.shape

torch.Size([1, 5])

In [12]:
weights.view(5,1).shape

torch.Size([5, 1])

In [13]:
mul = torch.mm(features, torch.t(weights))   #mul = torch.mm(features, weights.view(5,1))

In [14]:
mul

tensor([[-1.9796]])

In [15]:
mul.shape

torch.Size([1, 1])

In [16]:
bias.shape

torch.Size([1, 1])

In [17]:
net_input_h = mul + bias

In [18]:
y = sigmodal_activation(net_input_h)

In [19]:
y

tensor([[0.1595]])

In [20]:
torch.manual_seed(7)

In [21]:
features = torch.randn(1,3)

In [22]:
features

tensor([[-0.1468,  0.7861,  0.9468]])

In [23]:
n_input = features.shape[1]
n_hidden = 2
n_output = 1

In [24]:
W1 = torch.randn(n_input,n_hidden)

In [25]:
W1

tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])

In [26]:
W2 = torch.randn(n_hidden,n_output)

In [27]:
W2

tensor([[-1.6822],
        [ 0.3177]])

In [29]:
B1 = torch.randn(n_input)

In [ ]:
B1

In [ ]:
B2 = torch.randn(n_hidden)

In [ ]:
B2

In [ ]:
features

In [ ]:
h = torch.matmul(features,W1)